### PR TITLE
Bug fixes for animations and transitions between DemoSettings states

### PR DESCRIPTION
**Pull request by rachelrosengoogle**
Mostly fixes https://github.com/conversationai/perspectiveapi-authorship-demo/issues/32

There might still be a few edge cases where this is broken, because when I'm aggressively trying to break it with manual testing (e.g. typing into the textbox and also clicking between states) where I've seen the emoji "learn more" be in the wrong position, but this is overwhelmingly better than the previous completely broken state, and I can't reliably reproduce any of these edge cases.

Tests will come later, this is needed for instrument to run QA.

### CODE REVIEW

**Comment by gracelauren** [comment]
looking through this now

**Comment by gracelauren** [comment]
switching between the emoji and icon states with 'hide icon after load' produces this state:
https://cl.ly/1O3o32320L3I

**Comment by rachelrosengoogle** [comment]
That's because hideLoadingIconAfterLoad is set to true for Emoji, which causes the left shift of the other elements (there is no current support for hideLoadingIconAfterLoad for the emoji state, just the circle/square/diamond state). If you turn it off it doesn't happen. I had a local code change I made to reflect this which I was testing against, I made a PR: https://github.com/Jigsaw-Code/conversationai-website/pull/726

**Comment by gracelauren** [comment]
ahhh ok 👍

**Pull request merged**
